name: My Grades pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout the repository 
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install packages 
      run: npm install 
    - name: Run unit tests
      run: npm run test:unit

  test_UI:

    runs-on: ubuntu-latest
    needs: build_and_unit_test


    steps:
    - name: Checkout the repository 
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install packages 
      run: npm install 
    - name: Run UI tests
      run: npm run test:ui